[project]
name = "ai-agent-portfolio-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks-connect>=16.1.6",
    "pydantic-ai>=1.4.0",
]
